[package]
name = "migtd-collateral-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
curl = "0.4.44"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
percent-encoding = "2.3"
x509-parser = "0.15"