name: 'Setup Build Environment'
description: 'Install all dependencies needed for building MigTD'
inputs:
  install-jq:
    description: 'Whether to install jq (needed for policy v2 tests)'
    required: false
    default: 'false'
  install-tpm-tools:
    description: 'Whether to install TPM tools (libtss2-dev pkg-config)'
    required: false
    default: 'false'
  rust-toolchain:
    description: 'Rust toolchain version to install'
    required: false
    default: '1.88.0'
  add-x86-target:
    description: 'Whether to add x86_64-unknown-none target'
    required: false
    default: 'true'
  run-preparation:
    description: 'Whether to run preparation script'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@98e68e10c96dffcb7bfed8b2144541a66b49aa02 # v2.0.8
      with:
        version: "10.0"
        directory: ${{ runner.temp }}/llvm

    - name: Install libtinfo5
      shell: bash
      run: sudo apt-get update -y && sudo apt-get install libtinfo5 -y

    - name: Install NASM
      uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2

    - name: Install build dependencies
      shell: bash
      run: |
        PACKAGES="build-essential ocaml ocamlbuild automake autoconf libtool wget python-is-python3 libssl-dev git cmake perl"
        if [[ "${{ inputs.install-tpm-tools }}" == "true" ]]; then
          PACKAGES="$PACKAGES libtss2-dev pkg-config"
        fi
        if [[ "${{ inputs.install-jq }}" == "true" ]]; then
          PACKAGES="$PACKAGES jq"
        fi
        sudo apt-get install $PACKAGES -y

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        toolchain: ${{ inputs.rust-toolchain }}
        override: true
        components: rust-src

    - name: Add x86_64-unknown-none target
      if: inputs.add-x86-target == 'true'
      shell: bash
      run: rustup target add x86_64-unknown-none

    - name: Run preparation script
      if: inputs.run-preparation == 'true'
      shell: bash
      run: bash sh_script/preparation.sh
