on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

name: Library Crates

env:
  AS: nasm
  AR: llvm-ar
  CC: clang
  RUST_TOOLCHAIN: 1.88.0
  TOOLCHAIN_PROFILE: minimal

permissions:
  contents: read

jobs:
  lib-test:
    name: Build Library Crates
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
        with:
          rust-toolchain: '1.88.0' # for spdm-rs

      - name: Build library crates
        run: cargo xtask lib-build
      
      - name: Test library crates
        run: cargo xtask lib-test